"""Add password and click limit to URL model

Revision ID: 9bdbe34a72f0
Revises: cc8bf2e0a20b
Create Date: 2025-08-12 02:04:32.756789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bdbe34a72f0'
down_revision: Union[str, Sequence[str], None] = 'cc8bf2e0a20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('password', sa.String(), nullable=True))
    op.add_column('urls', sa.Column('max_clicks', sa.Integer(), nullable=True))
    op.add_column('urls', sa.Column('current_clicks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'current_clicks')
    op.drop_column('urls', 'max_clicks')
    op.drop_column('urls', 'password')
    # ### end Alembic commands ###
