# .github/workflows/ci.yml

name: Continuous Integration Pipeline

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build and run Docker services
        # CORREÇÃO: Usando 'docker compose' (com espaço)
        run: docker compose up --build -d

      - name: Wait for services
        run: sleep 15

      - name: Run database migrations
        # CORREÇÃO: Usando 'docker compose' (com espaço)
        run: docker compose exec -T api alembic upgrade head

      - name: Run Pytest
        # CORREÇÃO: Usando 'docker compose' (com espaço)
        run: docker compose exec -T api pytest --cov=Backend

      - name: Stop Docker services
        if: always()
        # CORREÇÃO: Usando 'docker compose' (com espaço)
        run: |
            touch .env
            docker compose down